In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

In [2]:
df2=pd.read_csv('./Heart_Disease_Prediction.csv')
df2.head(20)

Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0    70    1                4  130          322             0            2   
1    67    0                3  115          564             0            2   
2    57    1                2  124          261             0            0   
3    64    1                4  128          263             0            0   
4    74    0                2  120          269             0            2   
5    65    1                4  120          177             0            0   
6    56    1                3  130          256             1            2   
7    59    1                4  110          239             0            2   
8    60    1                4  140          293             0            2   
9    63    0                4  150          407             0            2   
10   59    1                4  135          234             0            0   
11   53    1                4  142          226             0            2   
12   44    1                3  140          235             0            2   
13   61    1                1  134          234             0            0   
14   57    0                4  128          303             0            2   
15   71    0                4  112          149             0            0   
16   46    1                4  140          311             0            0   
17   53    1                4  140          203             1            2   
18   64    1                1  110          211             0            2   
19   40    1                1  140          199             0            0   

    Max HR  Exercise angina  ST depression  Slope of ST  \
0      109                0            2.4            2   
1      160                0            1.6            2   
2      141                0            0.3            1   
3      105                1            0.2            2   
4      121                1            0.2            1   
5      140                0            0.4            1   
6      142                1            0.6            2   
7      142                1            1.2            2   
8      170                0            1.2            2   
9      154                0            4.0            2   
10     161                0            0.5            2   
11     111                1            0.0            1   
12     180                0            0.0            1   
13     145                0            2.6            2   
14     159                0            0.0            1   
15     125                0            1.6            2   
16     120                1            1.8            2   
17     155                1            3.1            3   
18     144                1            1.8            2   
19     178                1            1.4            1   

    Number of vessels fluro  Thallium Heart Disease  
0                         3         3      Presence  
1                         0         7       Absence  
2                         0         7      Presence  
3                         1         7       Absence  
4                         1         3       Absence  
5                         0         7       Absence  
6                         1         6      Presence  
7                         1         7      Presence  
8                         2         7      Presence  
9                         3         7      Presence  
10                        0         7       Absence  
11                        0         7       Absence  
12                        0         3       Absence  
13                        2         3      Presence  
14                        1         3       Absence  
15                        0         3       Absence  
16                        2         7      Presence  
17                        0         7      Presence  
18                        0         3       Absence  
19                        0         7       A

In [3]:
x=df2.iloc[:,:-1]
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
df2['Heart Disease']=label_encoder.fit_transform(df2['Heart Disease'])
y=df2['Heart Disease']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

from sklearn.tree import DecisionTreeClassifier
dectree=DecisionTreeClassifier()
dectree.fit(x_train,y_train)
predDecTree=dectree.predict(x_test)
scoreDecTree=dectree.score(x_test,y_test)
scoreDecTree


0.6851851851851852

In [4]:
print(dectree.predict([[64,1,4,128,263,0,0,105,1,0.2,2,1,7]]))
confusion_matrix(y_test, predDecTree)

[0]


c:\Users\shrey\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([[21,  8],
       [ 9, 16]], dtype=int64)

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df2['BP'] = scaler.fit_transform(df2[['BP']])
df2['Cholesterol'] = scaler.fit_transform(df2[['Cholesterol']])
df2['Max HR'] = scaler.fit_transform(df2[['Max HR']])
df2

Age  Sex  Chest pain type        BP  Cholesterol  FBS over 120  \
0     70    1                4  0.339623     0.447489             0   
1     67    0                3  0.198113     1.000000             0   
2     57    1                2  0.283019     0.308219             0   
3     64    1                4  0.320755     0.312785             0   
4     74    0                2  0.245283     0.326484             0   
..   ...  ...              ...       ...          ...           ...   
265   52    1                3  0.735849     0.166667             1   
266   44    1                2  0.245283     0.312785             0   
267   56    0                2  0.433962     0.383562             0   
268   57    1                4  0.433962     0.150685             0   
269   67    1                4  0.622642     0.365297             0   

     EKG results    Max HR  Exercise angina  ST depression  Slope of ST  \
0              2  0.290076                0            2.4            2   
1              2  0.679389                0            1.6            2   
2              0  0.534351                0            0.3            1   
3              0  0.259542                1            0.2            2   
4              2  0.381679                1            0.2            1   
..           ...       ...              ...            ...          ...   
265            0  0.694656                0            0.5            1   
266            0  0.778626                0            0.0            1   
267            2  0.625954                0            1.3            2   
268            0  0.587786                0            0.4            2   
269            2  0.282443                1            1.5            2   

     Number of vessels fluro  Thallium  Heart Disease  
0                          3         3              1  
1                          0         7              0  
2                          0         7              1  
3                          1         7              0  
4                          1         3              0  
..                       ...       ...            ...  
265                        0         7              0  
266                        0         7              0  
267                        0         3              0  
268                        0         6              0  
269                        3         3              1  

[270 rows x 14 columns]

In [6]:
x=df2.iloc[:,:-1]
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
df2['Heart Disease']=label_encoder.fit_transform(df2['Heart Disease'])
y=df2['Heart Disease']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [7]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(solver='lbfgs',max_iter=20000)
lr.fit(x_train,y_train)

predlr=lr.predict(x_test)
score=lr.score(x_test,y_test)
score

0.8888888888888888

In [8]:
lr.predict([[64,1,4,0.320755,0.312785,0,0,0.259542,1,0.2,2,1,7]])

c:\Users\shrey\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [9]:
confusion_matrix(y_test, predlr)

array([[29,  3],
       [ 3, 19]], dtype=int64)